# Generated by Django 5.0.2 on 2024-02-11 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
                ('sign_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency_in_days', models.IntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(max_length=250, verbose_name='Вознаграждение')),
                ('time_to_complete', models.TimeField(verbose_name='Время, потраченное на привычку')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habit.habit', verbose_name='Связанная привычка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place', to='habit.place', verbose_name='Место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
