# Generated by Django 5.0.2 on 2024-02-13 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='associated_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка'),
        ),
    ]
